name: 'PROS Build'
description: 'Build PROS C++ project'
branding:
  icon: 'box'  
  color: 'green'
inputs:
  path:
    description: 'Path to Project'
    required: false
    default: '.'
defaults:
  run:
    working-directory: inputs.path
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    --platform: 'linux/amd64'
