name: Release

on:
  push:
    branches: [ master ]

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    - name: release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: true
        release_name: ${{ steps.version.outputs.version }}x
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
