name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: ${{ github.event.head_commit.message }}
        tag_name: ${{ github.event.head_commit.message }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
